import type { Metadata } from 'next';
import { Lora, Merriweather } from 'next/font/google';
import './globals.css';
import { FC } from 'react';
import Navbar from 'components/layout/navbar';

const lora = Lora({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-lora',
  display: 'auto',
});

const merriweather = Merriweather({
  weight: ['400'],
  variable: '--font-merriweather',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html className={`${lora.className} ${merriweather.variable}`} lang="en">
      <body className="bg-eerieblack" suppressHydrationWarning>
        <Navbar />
        <main className="flex min-h-[calc(100svh-3.5rem)] flex-col items-center md:min-h-[calc(100svh-4.5rem)]">
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
