import type { Metadata } from 'next'
import { Merriweather, Lora } from 'next/font/google'
import './globals.css'
import { FC } from 'react'

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
  // weight: ["400", "600", "700"],
  display: 'swap',
})

const merriweather = Merriweather({
  weight: ['400', '700'],
  variable: '--font-merriweather',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<{
  children: React.ReactNode
}> = ({ children }) => {
  return (
    <html className={`${lora.variable} ${merriweather.variable}`} lang="en">
      <body suppressHydrationWarning>
        <main className="flex min-h-screen flex-col items-center justify-between">
          {children}
        </main>
      </body>
    </html>
  )
}

export default RootLayout
