import type { Metadata } from 'next';
import { Merriweather, Lora } from 'next/font/google';
import './globals.css';
import { FC } from 'react';
import Navbar from 'components/layout/navbar';

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
  // weight: ["400", "600", "700"],
  display: 'swap',
});

const merriweather = Merriweather({
  weight: ['400', '700'],
  variable: '--font-merriweather',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html className={`${lora.variable} ${merriweather.variable}`} lang="en">
      <body suppressHydrationWarning>
        <Navbar />
        <main className="flex min-h-[calc(100svh-4rem)] flex-col items-center justify-between bg-eerieblack md:min-h-[calc(100svh-5rem)]">
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
